drop table if exists book;

CREATE TABLE book
(
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author VARCHAR NOT NULL,
    title  VARCHAR NOT NULL,
    year   INT CHECK (year >= 1000 AND year <= 3000),
    people_id INT REFERENCES people(id),
    time_of_given TIMESTAMP
);

INSERT INTO book(author, title, year, people_id, time_of_given)
VALUES ('George Orwell', '1984', 1948, 1,'25-May-2016 10:30');
INSERT INTO book(author, title, year, people_id, time_of_given)
VALUES ('William Shakespeare', 'Hamlet', 1601, 1, '26-Jun-2022 13:54');
INSERT INTO book(author, title, year, people_id, time_of_given)
VALUES ('Ernest Hemingway', 'The Old Man and the Sea', 1952, null, null);

SELECT * FROM book ORDER BY id;